---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: ca-rocky
    image: geerlingguy/docker-rockylinux8-ansible:latest
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
