galaxy_info:
  author: mrplatinum
  namespace: mrplatinum
  role_name: common
  description: Base configuration applied to all nodes in all environments
  company: mrplatinum homelab
  license: MIT
  min_ansible_version: "2.9"
  galaxy_tags: []

dependencies: []
