---
clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      skip_verify: true

when:
  branch: main
  event: push

steps:
  - name: lint
    image: node1:3000/mrplatinum/ansible-lint:26.4.0
    pull: true
    environment:
      ANSIBLE_CONFIG: /woodpecker/src/node1/mrplatinum/ansible-sandbox/ansible.cfg
      VAULT_PASSWORD:
        from_secret: vault_password
    commands:
      - echo "$VAULT_PASSWORD" > secret.txt
      - ansible-lint
      - rm -f secret.txt
