---
when:
  branch: main
  event: push

steps:
  - name: lint
    image: node1:3000/mrplatinum/ansible-lint:6.22.2
    pull: true
    commands:
      - ansible-lint -c /woodpecker/src/node1/mrplatinum/ansible-sandbox/ansible.cfg
