---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: rocky9-promtail-test
    image: geerlingguy/docker-rockylinux9-ansible:latest
    pre_build_image: true
    privileged: false
    cgroupns_mode: host
    capabilities:
      - SYS_ADMIN
    command: /usr/sbin/init

  - name: ubuntu22-promtail-test
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    pre_build_image: true
    privileged: false
    cgroupns_mode: host
    capabilities:
      - SYS_ADMIN
    command: /usr/sbin/init
provisioner:
  name: ansible
  env:
    ANSIBLE_VAULT_PASSWORD_FILE: "~/projects/ansible-sandbox/secret.txt"
  playbooks:
    prepare: prepare.yml
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python3
        env_name: molecule
        loki_url: "https://mock-loki.example.com:3100"
verifier:
  name: ansible
