# Ansible Sandbox Inventory
# Add your managed nodes here as you set them up

[control]
localhost ansible_connection=local

[physical_nodes]
# rocky01 ansible_host=192.168.1.X
# rocky02 ansible_host=192.168.1.X

[docker_nodes]
# container01 ansible_host=172.17.0.X ansible_port=22

[cloud_nodes]
# oracle01 ansible_host=<public-ip>

[lab:children]
physical_nodes
docker_nodes

[all:vars]
ansible_python_interpreter=/usr/bin/python3
