---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: rocky9-immich-test
    image: docker.io/geerlingguy/docker-rockylinux9-ansible:latest
    pre_build_image: true
    privileged: false
    capabilities:
      - SYS_ADMIN
    cgroupns_mode: host
    command: /usr/sbin/init
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python3
        env_name: molecule
verifier:
  name: ansible
