[prod]
node1

[rocky]
node1

[monitoring]
aws-monitoring

[cloud]
aws-monitoring

[all:vars]
ansible_python_interpreter=/usr/bin/python3

[pihole]
node1

[jellyfin]
node1

[nextcloud]
node1

[immich]
node1
