---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: rocky8-gitea-test
    image: docker.io/geerlingguy/docker-rockylinux8-ansible:latest
    pre_build_image: true
    privileged: true
    command: /usr/sbin/init
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python3
        env_name: molecule
        vault_gitea_db_password: "molecule_test_db_pass"
        vault_gitea_secret_key: "molecule_test_secret_key_use_32_chars_minimum_here"
        vault_mariadb_root_password: "molecule_test_root_pass"
        vault_gitea_internal_token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE3Nzg4MTY0NjN9.HXrq4zG_IB3l063cH2Xvp451P41J28-cYYk5DEaodns"
        vault_gitea_jwt_secret: "_5SYz_LyfOcLfjmEvvvKY0beva9_RsRqEodCJGDpBqY"
verifier:
  name: ansible
