---
- name: Restart php-fpm
  ansible.builtin.systemd:
    name: "{{ nextcloud_php_fpm_pkg }}"
    state: restarted
  when: env_name != 'molecule'

- name: Reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
  when:
    - env_name != 'molecule'
    - ansible_os_family == 'RedHat'

- name: Restart apache
  ansible.builtin.systemd:
    name: apache2
    state: restarted
  when: env_name != 'molecule'
