---
ca_dir: "{{ lookup('env', 'HOME') }}/.ansible-sandbox-ca"

ca_common_name: "Ansible Sandbox Local CA"
ca_org: "Home Lab"
ca_country: "US"

ca_key_size: 4096
ca_validity_days: 3650
ca_node_cert_validity_days: 825

ca_node_cert_cn: "{{ inventory_hostname }}"
